backport use-kbuild-compiler.patch from 355.11
git-svn-id: svn://svn.debian.org/svn/pkg-nvidia/packages/nvidia-graphics-drivers/trunk@6116 b6a4b1ba-b714-0410-8a2d-fc0b36c6496e

diff --git a/debian/module/debian/patches/not-silent.patch b/debian/module/debian/patches/not-silent.patch
--- a/debian/module/debian/patches/not-silent.patch
+++ b/debian/module/debian/patches/not-silent.patch
@@ -79,15 +79,15 @@ Description: make silent commands in NVIDIA's Makefile.kbuild verbose
  	 if ! $(CONFTEST) $$SANITY_CHECK full_output; then \
  	 exit 1; \
  	 fi; \
-@@ -242,7 +242,7 @@ build-sanity-checks:
- #
- 
- module: build-sanity-checks $(CONFTEST_HEADERS)
--	@echo "NVIDIA: calling KBUILD..."; \
-+	$(NVQ)echo "NVIDIA: calling KBUILD..."; \
- 	$(MAKE) "CC=$(CC)" $(KBUILD_PARAMS) modules; \
- 	echo "NVIDIA: left KBUILD."; \
- 	for module in $(MODULE_OBJECTS); do \
+@@ -245,7 +245,7 @@ module: build-sanity-checks $(CONFTEST_H
+ 	@echo "NVIDIA: calling KBUILD..."
+ 	$(MAKE) $(KBUILD_PARAMS) modules
+ 	@echo "NVIDIA: left KBUILD."
+-	for module in $(MODULE_OBJECTS); do \
++	$(NVQ)for module in $(MODULE_OBJECTS); do \
+ 	if ! [ -f $$module ]; then \
+ 	 echo "$$module failed to build!"; \
+ 	 exit 1; \
 @@ -260,7 +260,7 @@ module: build-sanity-checks $(CONFTEST_H
  #
  
