* debian/*.postinst(configure): abort early if DPKG_MAINTSCRIPT_PACKAGE is   not set (usually if called from dpkg-reconfigure, see #560317)
git-svn-id: svn://svn.debian.org/svn/pkg-nvidia/packages/nvidia-graphics-drivers/branches/256.xx-experimental@1491 b6a4b1ba-b714-0410-8a2d-fc0b36c6496e

diff --git a/debian/libgl1-nvidia-alternatives-ia32.postinst b/debian/libgl1-nvidia-alternatives-ia32.postinst
--- a/debian/libgl1-nvidia-alternatives-ia32.postinst
+++ b/debian/libgl1-nvidia-alternatives-ia32.postinst
@@ -34,6 +34,13 @@ exists()
 if [ "$1" = "configure" ]
 then
 
+	# dpkg-reconfigure does not set DPKG_MAINTSCRIPT_PACKAGE (#560317)
+	if [ -z "$DPKG_MAINTSCRIPT_PACKAGE" ]
+	then
+		echo "ERROR: DPKG_MAINTSCRIPT_PACKAGE is not set, usually a bug in dpkg-reconfigure"
+		exit 1
+	fi
+
 	# <target: squeeze>
 	if [ -L "/usr/lib32" ] && \
 		[ "$(readlink /usr/lib32)" = "/emul/ia32-linux/usr/lib" ]
