merge some missing conflicts and workarounds from the experimental 256.xx branch
git-svn-id: svn://svn.debian.org/svn/pkg-nvidia/packages/nvidia-graphics-drivers/trunk@1518 b6a4b1ba-b714-0410-8a2d-fc0b36c6496e

diff --git a/debian/libgl1-nvidia-alternatives-ia32.postinst b/debian/libgl1-nvidia-alternatives-ia32.postinst
--- a/debian/libgl1-nvidia-alternatives-ia32.postinst
+++ b/debian/libgl1-nvidia-alternatives-ia32.postinst
@@ -34,6 +34,24 @@ exists()
 if [ "$1" = "configure" ]
 then
 
+	# dpkg-reconfigure does not set DPKG_MAINTSCRIPT_PACKAGE (#560317)
+	if [ -z "$DPKG_MAINTSCRIPT_PACKAGE" ]
+	then
+		echo "ERROR: DPKG_MAINTSCRIPT_PACKAGE is not set, usually a bug in dpkg-reconfigure"
+		exit 1
+	fi
+
+	# <target: squeeze>
+	if [ -L "/usr/lib32" ] && \
+		[ "$(readlink /usr/lib32)" = "/emul/ia32-linux/usr/lib" ]
+	then
+		echo "ERROR: /usr/lib32 is a symbolic link to /emul/ia32-linux/usr/lib"
+		echo "       Please reinstall libc6-i386!"
+		echo "       Aborting configuration of $DPKG_MAINTSCRIPT_PACKAGE"
+		exit 1
+	fi
+	# </target: squeeze>
+
 	# <target: squeeze>
 	# take over diversions from nvidia-glx{,-legacy-*xx}-ia32
 	for file in libGL.so.1.2 libGL.so.1 libGL.so
diff --git a/debian/libglx-nvidia-alternatives.postinst b/debian/libglx-nvidia-alternatives.postinst
--- a/debian/libglx-nvidia-alternatives.postinst
+++ b/debian/libglx-nvidia-alternatives.postinst
@@ -26,6 +26,13 @@ exists()
 if [ "$1" = "configure" ]
 then
 
+	# dpkg-reconfigure does not set DPKG_MAINTSCRIPT_PACKAGE (#560317)
+	if [ -z "$DPKG_MAINTSCRIPT_PACKAGE" ]
+	then
+		echo "ERROR: DPKG_MAINTSCRIPT_PACKAGE is not set, usually a bug in dpkg-reconfigure"
+		exit 1
+	fi
+
 	# the destination directory for the diversions
 	test -d /usr/lib/nvidia/diversions || \
 		mkdir -p /usr/lib/nvidia/diversions || true
diff --git a/debian/nvidia-glx-dev.postinst b/debian/nvidia-glx-dev.postinst
--- a/debian/nvidia-glx-dev.postinst
+++ b/debian/nvidia-glx-dev.postinst
@@ -5,6 +5,13 @@ set -e
 case "$1" in
     configure)
 
+	# dpkg-reconfigure does not set DPKG_MAINTSCRIPT_PACKAGE (#560317)
+	if [ -z "$DPKG_MAINTSCRIPT_PACKAGE" ]
+	then
+		echo "ERROR: DPKG_MAINTSCRIPT_PACKAGE is not set, usually a bug in dpkg-reconfigure"
+		exit 1
+	fi
+
         # <target: squeeze>
         if dpkg --compare-versions "$2" lt-nl 195.36.24-1 ; then
             # remove obsolete diversions
diff --git a/debian/nvidia-glx.postinst b/debian/nvidia-glx.postinst
--- a/debian/nvidia-glx.postinst
+++ b/debian/nvidia-glx.postinst
@@ -2,6 +2,18 @@
 set -e
 
 
+if [ "$1" = "configure" ]
+then
+
+	# dpkg-reconfigure does not set DPKG_MAINTSCRIPT_PACKAGE (#560317)
+	if [ -z "$DPKG_MAINTSCRIPT_PACKAGE" ]
+	then
+		echo "ERROR: DPKG_MAINTSCRIPT_PACKAGE is not set, usually a bug in dpkg-reconfigure"
+		exit 1
+	fi
+
+fi
+
 # <target: squeeze>
 dpkg-maintscript-helper rm_conffile /etc/default/$DPKG_MAINTSCRIPT_PACKAGE 195.36.24-1~ -- "$@"
 dpkg-maintscript-helper rm_conffile /etc/init.d/$DPKG_MAINTSCRIPT_PACKAGE 195.36.24-3~ -- "$@"
