ia32 transition
git-svn-id: svn://svn.debian.org/svn/pkg-nvidia/packages/nvidia-graphics-drivers/trunk@562 b6a4b1ba-b714-0410-8a2d-fc0b36c6496e

diff --git a/debian/nvidia-glx-ia32.postinst b/debian/nvidia-glx-ia32.postinst
--- a/debian/nvidia-glx-ia32.postinst
+++ b/debian/nvidia-glx-ia32.postinst
@@ -1,14 +1,55 @@
 #!/bin/sh
+# postinst script for nvidia-glx-ia32
+#
+# see: dh_installdeb(1)
 
 set -e
 
+# summary of how this script can be called:
+#        * <postinst> `configure' <most-recently-configured-version>
+#        * <old-postinst> `abort-upgrade' <new version>
+#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
+#          <new-version>
+#        * <postinst> `abort-remove'
+#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
+#          <failed-install-package> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
 
 
+case "$1" in
+    configure)
 
+	# remove diversion created before the
+	# /emul/ia32-linux/usr/lib => /usr/lib32 transition
+	dpkg-divert --remove --rename --package nvidia-glx-ia32 --divert \
+		/emul/ia32-linux/usr/lib/nvidia/libGL.so.ia32-libs \
+		/emul/ia32-linux/usr/lib/libGL.so > /dev/null
+	dpkg-divert --remove --rename --package nvidia-glx-ia32 --divert \
+		/emul/ia32-linux/usr/lib/nvidia/libGL.so.1.ia32-libs \
+		/emul/ia32-linux/usr/lib/libGL.so.1 > /dev/null
+	dpkg-divert --remove --rename --package nvidia-glx-ia32 --divert \
+		/emul/ia32-linux/usr/lib/nvidia/libGL.so.1.2.ia32-libs \
+		/emul/ia32-linux/usr/lib/libGL.so.1.2 > /dev/null
 
+	test -d /emul/ia32-linux/usr/lib/nvidia && \
+		rmdir /emul/ia32-linux/usr/lib/nvidia || true;
+
+    ;;
+
+    abort-upgrade|abort-remove|abort-deconfigure)
+    ;;
+
+    *)
+        echo "postinst called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
+esac
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
 
 #DEBHELPER#
 
-
-
-ldconfig
+exit 0
