General maintainer script cleanup
* maintainer scripts:
  - synchronize with dh_make templates
  - document the target release squeeze for some cleanup operations as a
    hint to remove them after squeeze release
  - remove code deactivated before etch release
  - remove diversion transition and cleanup code introduced before etch
    release
  - remove libwfb.so diversion cleanup code introduced before lenny release


git-svn-id: svn://svn.debian.org/svn/pkg-nvidia/packages/nvidia-graphics-drivers/trunk@827 b6a4b1ba-b714-0410-8a2d-fc0b36c6496e

diff --git a/debian/nvidia-glx-dev.postrm b/debian/nvidia-glx-dev.postrm
--- a/debian/nvidia-glx-dev.postrm
+++ b/debian/nvidia-glx-dev.postrm
@@ -1,48 +1,52 @@
-#! /bin/sh
-# postrm script for nvidia-glx
+#!/bin/sh
+# postrm script for nvidia-glx-dev
 #
 # see: dh_installdeb(1)
 
 set -e
 
+# summary of how this script can be called:
+#        * <postrm> `remove'
+#        * <postrm> `purge'
+#        * <old-postrm> `upgrade' <new-version>
+#        * <new-postrm> `failed-upgrade' <old-version>
+#        * <new-postrm> `abort-install'
+#        * <new-postrm> `abort-install' <old-version>
+#        * <new-postrm> `abort-upgrade' <old-version>
+#        * <disappearer's-postrm> `disappear' <overwriter>
+#          <overwriter-version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
+
+# released versions: etch: 1.0.8776-4, lenny: 173.14.09-5
+
 case "$1" in
-    remove|purge)
-#	dpkg-divert --remove --rename --package nvidia-glx-dev --divert /usr/lib/nvidia/libGL.so.xlibmesa /usr/lib/libGL.so > /dev/null
-#	dpkg-divert --remove --rename --package nvidia-glx-dev --divert /usr/lib/nvidia/libGL.so.xlibmesa /usr/lib/libGL.so > /dev/null
+    purge|remove)
+
         rm /usr/lib/libGL.so || true
 	invoke-rc.d nvidia-glx start || true		
-#	ln -s /usr/lib/nvidia/libGL.so.1.2.xlibmesa /usr/lib/libGL.so
-	
 
+	# this diversion is no longer being created since r93 = 1.0.8774-5
 	dpkg-divert --remove --rename --package nvidia-glx-dev --divert /usr/lib/nvidia/libGL.a.xlibmesa  /usr/lib/libGL.a > /dev/null
-
-#	dpkg-divert --remove --rename --package nvidia-glx-dev --divert /usr/share/nvidia-glx/diversions/gl.h /usr/include/GL/gl.h > /dev/null
-#	dpkg-divert --remove --rename --package nvidia-glx-dev --divert /usr/share/nvidia-glx/diversions/glx.h /usr/include/GL/glx.h > /dev/null
-#	dpkg-divert --remove --rename --package nvidia-glx-dev --divert /usr/share/nvidia-glx/diversions/glxtokens.h /usr/include/GL/glxtokens.h > /dev/null
-
-#	dpkg-divert --remove --rename --package nvidia-glx-dev --divert /usr/share/nvidia-glx/diversions/gl.h /usr/include/GL/gl.h > /dev/null
-#	dpkg-divert --remove --rename --package nvidia-glx-dev --divert /usr/share/nvidia-glx/diversions/glx.h /usr/include/GL/glx.h > /dev/null
-#	dpkg-divert --remove --rename --package nvidia-glx-dev --divert /usr/share/nvidia-glx/diversions/glxtokens.h /usr/include/GL/glxtokens.h > /dev/null
 
 	if [ -d /usr/lib/nvidia/ ]; then
 		rmdir /usr/lib/nvidia || true;
-
 	fi
 
     ;;
-    
+
     upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
-
-
-        ;;
+    ;;
 
     *)
         echo "postrm called with unknown argument \`$1'" >&2
-        exit 0
-
+        exit 1
+    ;;
 esac
 
 # dh_installdeb will replace this with shell code automatically
 # generated by other debhelper scripts.
 
 #DEBHELPER#
+
+exit 0
diff --git a/debian/nvidia-glx.postinst b/debian/nvidia-glx.postinst
--- a/debian/nvidia-glx.postinst
+++ b/debian/nvidia-glx.postinst
@@ -1,6 +1,22 @@
 #!/bin/sh
+# postinst script for nvidia-glx
+#
+# see: dh_installdeb(1)
 
 set -e
+
+# summary of how this script can be called:
+#        * <postinst> `configure' <most-recently-configured-version>
+#        * <old-postinst> `abort-upgrade' <new version>
+#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
+#          <new-version>
+#        * <postinst> `abort-remove'
+#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
+#          <failed-install-package> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
+
 
 rm_conffile() {
   mv_conffile "$1" "$1.dpkg-bak"
@@ -24,12 +40,15 @@ mv_conffile() {
   fi
 }
 
-case "$1" in 
+
+case "$1" in
     configure)
 
+	# <target: squeeze>
         if dpkg --compare-versions "$2" lt-nl 190.53-5 ; then
             rm_conffile /etc/default/nvidia-glx
         fi 
+	# </target: squeeze>
 
     ;;
 
@@ -37,21 +56,14 @@ case "$1" in
     ;;
 
     *)
-        echo "$0 called with unknown argument '$1'" >&2
+        echo "postinst called with unknown argument \`$1'" >&2
         exit 1
     ;;
 esac
 
-
-#make sure wfb diversion is removed
-dpkg-divert --rename --remove --package nvidia-glx --divert /usr/lib/nvidia/libwfb.so.xserver-xorg-core /usr/lib/xorg/modules/libwfb.so >/dev/null || true
-
-
-
-
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
 
 #DEBHELPER#
 
-
-
-ldconfig
+exit 0
diff --git a/debian/nvidia-glx.postrm.in b/debian/nvidia-glx.postrm.in
--- a/debian/nvidia-glx.postrm.in
+++ b/debian/nvidia-glx.postrm.in
@@ -1,7 +1,22 @@
-#! /bin/sh
+#!/bin/sh
 # postrm script for nvidia-glx
+#
+# see: dh_installdeb(1)
 
 set -e
+
+# summary of how this script can be called:
+#        * <postrm> `remove'
+#        * <postrm> `purge'
+#        * <old-postrm> `upgrade' <new-version>
+#        * <new-postrm> `failed-upgrade' <old-version>
+#        * <new-postrm> `abort-install'
+#        * <new-postrm> `abort-install' <old-version>
+#        * <new-postrm> `abort-upgrade' <old-version>
+#        * <disappearer's-postrm> `disappear' <overwriter>
+#          <overwriter-version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
 
 # Rationale:
 #
@@ -23,12 +38,14 @@ set -e
 # and assume that our overwriting package will have logic to take over the
 # diversions and doesn't want us messing with them.
 
+
 case "$1" in
     remove|abort-install)
         if [ remove = "$1" ] ; then
             # remove file created by init script
     	    rm /usr/lib/libGL.so || true
         fi
+
 	dpkg-divert --remove --rename --package nvidia-glx --divert /usr/lib/nvidia/libGL.so.1.xlibmesa /usr/lib/libGL.so.1 > /dev/null
 	dpkg-divert --remove --rename --package nvidia-glx --divert /usr/lib/nvidia/libGL.so.1.2.xlibmesa /usr/lib/libGL.so.1.2 > /dev/null
 	
@@ -42,28 +59,21 @@ case "$1" in
 	if [ -d /usr/lib/nvidia ]; then
 		rmdir /usr/lib/nvidia/ || true;
 	fi
-	ldconfig
-		
+
     ;;
-    
-    upgrade|failed-upgrade|abort-upgrade|disappear|purge)
 
-
-        ;;
+    purge|upgrade|failed-upgrade|abort-upgrade|disappear)
+    ;;
 
     *)
         echo "postrm called with unknown argument \`$1'" >&2
-        exit 0
-
+        exit 1
+    ;;
 esac
-
-
-#rm -f /usr/lib/xorg/modules/extensions/libglx.so.#VERSION# 2> /dev/null || true
-
-    
-
 
 # dh_installdeb will replace this with shell code automatically
 # generated by other debhelper scripts.
 
 #DEBHELPER#
+
+exit 0
